function AIShowcase() {

  return (

    <section className="bg-slate-950 py-24">


      <div className="max-w-7xl mx-auto px-8">


        <div className="text-center mb-16">


          <h2 className="
          text-5xl
          font-bold
          text-white
          ">
            Experience AI Powered Travel Planning
          </h2>


          <p className="
          text-gray-400
          mt-5
          text-lg
          ">
            See how Voyage AI transforms your ideas into complete travel plans.
          </p>


        </div>




        <div className="
        grid
        lg:grid-cols-2
        gap-12
        items-center
        ">



          {/* Left Content */}

          <div>


            <h3 className="
            text-4xl
            font-bold
            text-white
            mb-6
            ">
              Paris Adventure 🇫🇷
            </h3>


            <p className="
            text-gray-400
            text-lg
            mb-8
            ">
              A personalized 5-day itinerary generated by AI based on your interests and budget.
            </p>




            <div className="
            space-y-5
            ">


              <div className="
              bg-slate-900
              border
              border-slate-800
              rounded-2xl
              p-5
              ">

                <h4 className="text-white font-bold">
                  📅 Day 1
                </h4>

                <p className="text-gray-400 mt-2">
                  Eiffel Tower • Louvre Museum • Local Cuisine
                </p>

              </div>



              <div className="
              bg-slate-900
              border
              border-slate-800
              rounded-2xl
              p-5
              ">

                <h4 className="text-white font-bold">
                  📅 Day 2
                </h4>

                <p className="text-gray-400 mt-2">
                  Versailles Palace • Seine River Cruise
                </p>

              </div>



            </div>


          </div>





          {/* Dashboard Preview */}


          <div className="
          bg-slate-900
          border
          border-slate-800
          rounded-3xl
          p-8
          shadow-2xl
          ">


            <h3 className="
            text-2xl
            text-white
            font-bold
            mb-8
            ">
              Trip Overview
            </h3>




            <div className="
            grid
            grid-cols-2
            gap-5
            ">


              <div className="
              bg-slate-800
              rounded-xl
              p-5
              ">

                <p className="text-gray-400">
                  Duration
                </p>

                <h2 className="text-white text-3xl font-bold">
                  5 Days
                </h2>

              </div>



              <div className="
              bg-slate-800
              rounded-xl
              p-5
              ">

                <p className="text-gray-400">
                  Travelers
                </p>

                <h2 className="text-white text-3xl font-bold">
                  2
                </h2>

              </div>




              <div className="
              bg-slate-800
              rounded-xl
              p-5
              ">

                <p className="text-gray-400">
                  Budget
                </p>

                <h2 className="text-white text-3xl font-bold">
                  $1200
                </h2>

              </div>




              <div className="
              bg-slate-800
              rounded-xl
              p-5
              ">

                <p className="text-gray-400">
                  Rating
                </p>

                <h2 className="text-white text-3xl font-bold">
                  ⭐ 4.9
                </h2>

              </div>



            </div>



            <button className="
            mt-8
            w-full
            bg-blue-600
            hover:bg-blue-700
            text-white
            py-4
            rounded-xl
            font-semibold
            ">
              Generate Your Trip
            </button>


          </div>


        </div>


      </div>


    </section>

  );

}


export default AIShowcase;